// GENERATED BY tools/gen-kotlin.js - DO NOT EDIT BY HAND.

package com.sylcolabs.weatherpaper.scene

import com.sylcolabs.weatherpaper.R

/**
 * The scene, as one complete image per time of day.
 *
 * Imported from art/frames/ by tools/import-frames.js, which are themselves relit from the
 * source planes by art/relight.js. The renderer cross-fades between the two frames either side
 * of the current time, wrapping past midnight, so every frame shares its geometry with the rest
 * and differs only in light.
 */
internal object Frames {

    const val WIDTH = 160
    const val HEIGHT = 288

    /** How the artwork sits in a screen of a different shape once scaled to cover. */
    const val ANCHOR_BOTTOM = true

    /** @param phase position in the day: 0 midnight, 0.25 sunrise, 0.5 noon, 0.75 sunset. */
    class Frame(val name: String, val resId: Int, val phase: Float)

    /** Sorted by phase. */
    val ALL: Array<Frame> = arrayOf(
        Frame("night", R.drawable.frame_night, 0.0f),
        Frame("dawn", R.drawable.frame_dawn, 0.25f),
        Frame("morning", R.drawable.frame_morning, 0.34f),
        Frame("midday", R.drawable.frame_midday, 0.5f),
        Frame("golden", R.drawable.frame_golden, 0.68f),
        Frame("dusk", R.drawable.frame_dusk, 0.78f),
    )

    val isEmpty: Boolean get() = ALL.isEmpty()

    /**
     * The two frames bracketing [phase], and how far between them we are.
     *
     * Wraps past midnight, so the last frame of the day blends back into the first.
     */
    fun bracket(phase: Float): Triple<Int, Int, Float> {
        val n = ALL.size
        if (n <= 1) return Triple(0, 0, 0f)
        val p = ((phase % 1f) + 1f) % 1f

        var lo = n - 1
        for (i in ALL.indices) if (ALL[i].phase <= p) lo = i else break
        val hi = (lo + 1) % n

        val from = ALL[lo].phase
        var span = ALL[hi].phase - from
        if (span <= 0f) span += 1f                       // wrapping the midnight seam
        var travelled = p - from
        if (travelled < 0f) travelled += 1f

        return Triple(lo, hi, (travelled / span).coerceIn(0f, 1f))
    }
}
