// GENERATED BY tools/gen-kotlin.js - DO NOT EDIT BY HAND.

package com.sylcolabs.weatherpaper.scene

import com.sylcolabs.weatherpaper.R

/**
 * The scene, as a stack of images composited back to front.
 *
 * Imported from art/layers/ by tools/import-layers.js. Nothing here assumes anything about what
 * the picture contains - the canvas size comes from the artwork itself, and an empty list simply
 * means no art has been imported yet.
 */
internal object Layers {

    /** The artwork's own pixel dimensions; 0 when nothing has been imported. */
    const val WIDTH = 0
    const val HEIGHT = 0

    /** How the artwork sits in a screen of a different shape once it has been scaled to cover. */
    const val ANCHOR_BOTTOM = true

    /**
     * @param parallax how far this layer slides as the home screen is swiped, in artwork pixels.
     * @param sway amplitude of its idle drift, in artwork pixels. Zero for both means it is still.
     */
    class Layer(val name: String, val resId: Int, val parallax: Float, val sway: Float)

    /** Back to front. */
    val ALL: Array<Layer> = arrayOf()

    val isEmpty: Boolean get() = ALL.isEmpty()

    /** True while any layer drifts on its own, which is what decides if a redraw loop is needed. */
    val hasMotion: Boolean get() = ALL.any { it.sway != 0f }
}
