// GENERATED BY tools/gen-kotlin.js - DO NOT EDIT BY HAND.

package com.sylcolabs.weatherpaper.scene

import com.sylcolabs.weatherpaper.R

/**
 * The scene, as a stack of images composited back to front.
 *
 * Imported from art/layers/ by tools/import-layers.js. Nothing here assumes anything about what
 * the picture contains - the canvas size comes from the artwork itself, and an empty list simply
 * means no art has been imported yet.
 */
internal object Layers {

    /** The artwork's own pixel dimensions; 0 when nothing has been imported. */
    const val WIDTH = 160
    const val HEIGHT = 288

    /** How the artwork sits in a screen of a different shape once it has been scaled to cover. */
    const val ANCHOR_BOTTOM = true

    /**
     * @param parallax how far this layer slides as the home screen is swiped, in artwork pixels.
     * @param sway amplitude of its idle drift, in artwork pixels. Zero for both means it is still.
     */
    class Layer(val name: String, val resId: Int, val parallax: Float, val sway: Float)

    /** Back to front. */
    val ALL: Array<Layer> = arrayOf(
        Layer("sky", R.drawable.layer_01_sky, 0.0f, 0.0f),
        Layer("far-ridge", R.drawable.layer_02_far_ridge, 0.0f, 0.0f),
        Layer("mid-forest", R.drawable.layer_03_mid_forest, 0.0f, 0.0f),
        Layer("ground", R.drawable.layer_04_ground, 0.0f, 0.0f),
        Layer("river", R.drawable.layer_05_river, 0.0f, 0.0f),
        Layer("near-forest", R.drawable.layer_06_near_forest, 0.0f, 0.0f),
        Layer("shrubs", R.drawable.layer_07_shrubs, 0.0f, 0.0f),
        Layer("frame", R.drawable.layer_08_frame, 0.0f, 0.0f),
    )

    val isEmpty: Boolean get() = ALL.isEmpty()

    /** True while any layer drifts on its own, which is what decides if a redraw loop is needed. */
    val hasMotion: Boolean get() = ALL.any { it.sway != 0f }
}
