// GENERATED BY tools/gen-kotlin.js - DO NOT EDIT BY HAND.

package com.sylcolabs.weatherpaper.scene

/**
 * Fixed points in the artwork that the renderer needs to aim at.
 *
 * All in artwork pixels, measured from the art itself - not guessed, and not hand-copied.
 */
internal object SceneMeta {

    /** True when the artwork carried metadata; false leaves every effect that needs it switched off. */
    const val PRESENT = true

    /** The moon, on the star plane. Its light is what the scene is lit by. */
    const val MOON_X = 72
    const val MOON_Y = 44
    const val MOON_R = 3
    const val HAS_MOON = true

    /**
     * The cabin's window and doorway, left to right, as x, y, w, h.
     *
     * The cabin is unlit in the artwork, so the glow is drawn rather than painted in - which
     * means it can answer to the weather instead of being fixed.
     */
    val WINDOWS: Array<IntArray> = arrayOf(
        intArrayOf(100, 190, 2, 7),
        intArrayOf(114, 189, 2, 8),
    )
}
