'use strict';
// Turns the art data into Kotlin the app compiles against.
//   art/frames.json     -> scene/Frames.kt
//   art/scene-meta.json -> scene/SceneMeta.kt
//   art/font.json       -> scene/PixelFont.kt
// All three outputs are generated - edit the JSON and re-run, never the Kotlin.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'app/src/main/java/com/sylcolabs/weatherpaper/scene');
const PKG = 'package com.sylcolabs.weatherpaper.scene';
const HEADER = '// GENERATED BY tools/gen-kotlin.js - DO NOT EDIT BY HAND.\n';

function read(file, fallback) {
  const p = path.join(ROOT, file);
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : fallback;
}
const f = n => (Number.isInteger(n) ? n.toFixed(1) : String(n)) + 'f';

// ------------------------------------------------------------------ frames
const manifest = read('art/frames.json', { width: 0, height: 0, anchor: 'bottom', frames: [] });
const frames = manifest.frames || [];

const framesKt = `${HEADER}
${PKG}

import com.sylcolabs.weatherpaper.R

/**
 * The scene, as one complete image per time of day.
 *
 * Imported from art/frames/ by tools/import-frames.js, which are themselves relit from the
 * source planes by art/relight.js. The renderer cross-fades between the two frames either side
 * of the current time, wrapping past midnight, so every frame shares its geometry with the rest
 * and differs only in light.
 */
internal object Frames {

    const val WIDTH = ${manifest.width || 0}
    const val HEIGHT = ${manifest.height || 0}

    /** How the artwork sits in a screen of a different shape once scaled to cover. */
    const val ANCHOR_BOTTOM = ${manifest.anchor !== 'centre' && manifest.anchor !== 'center'}

    /** @param phase position in the day: 0 midnight, 0.25 sunrise, 0.5 noon, 0.75 sunset. */
    class Frame(val name: String, val resId: Int, val phase: Float)

    /** Sorted by phase. */
    val ALL: Array<Frame> = arrayOf(${frames.length === 0 ? ')' : '\n' +
  frames.map(fr => `        Frame("${fr.name}", R.drawable.${fr.resource}, ${f(fr.phase)}),`).join('\n') +
  '\n    )'}

    val isEmpty: Boolean get() = ALL.isEmpty()

    /**
     * The two frames bracketing [phase], and how far between them we are.
     *
     * Wraps past midnight, so the last frame of the day blends back into the first.
     */
    fun bracket(phase: Float): Triple<Int, Int, Float> {
        val n = ALL.size
        if (n <= 1) return Triple(0, 0, 0f)
        val p = ((phase % 1f) + 1f) % 1f

        var lo = n - 1
        for (i in ALL.indices) if (ALL[i].phase <= p) lo = i else break
        val hi = (lo + 1) % n

        val from = ALL[lo].phase
        var span = ALL[hi].phase - from
        if (span <= 0f) span += 1f                       // wrapping the midnight seam
        var travelled = p - from
        if (travelled < 0f) travelled += 1f

        return Triple(lo, hi, (travelled / span).coerceIn(0f, 1f))
    }
}
`;

// --------------------------------------------------------------- scene meta
const meta = read('art/scene-meta.json', null);
const openings = (meta && meta.cabin && meta.cabin.openings) || [];
const moon = (meta && meta.moon) || null;

const metaKt = `${HEADER}
${PKG}

/**
 * Fixed points in the artwork that the renderer needs to aim at.
 *
 * All in artwork pixels, measured from the art itself - not guessed, and not hand-copied.
 */
internal object SceneMeta {

    /** True when the artwork carried metadata; false leaves every effect that needs it off. */
    const val PRESENT = ${meta !== null}

    const val MOON_X = ${moon ? moon.x : 0}
    const val MOON_Y = ${moon ? moon.y : 0}
    const val MOON_R = ${moon ? moon.r : 0}
    const val HAS_MOON = ${moon !== null}

    /**
     * The cabin's window and doorway, left to right, as x, y, w, h.
     *
     * The cabin is unlit in every frame, so the lamp is drawn rather than painted in - which
     * means it can answer to the weather instead of being fixed.
     */
    val WINDOWS: Array<IntArray> = arrayOf(${openings.length === 0 ? ')' : '\n' +
  openings.map(o => `        intArrayOf(${o.x}, ${o.y}, ${o.w}, ${o.h}),`).join('\n') + '\n    )'}
}
`;

// -------------------------------------------------------------------- font
const font = read('art/font.json', { w: 5, h: 7, tracking: 1, glyphs: {} });
const order = Object.keys(font.glyphs);
const packed = order.map(function (ch) {
  const rows = font.glyphs[ch].split('/');
  let bits = 0n;
  for (let r = 0; r < font.h; r++) {
    for (let c = 0; c < font.w; c++) {
      if (rows[r][c] === '#') bits |= 1n << BigInt(r * font.w + c);
    }
  }
  return bits;
});
const index = order.join('').replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$');

const fontKt = `${HEADER}
${PKG}

/**
 * The bitmap font used by the home-screen readout, from art/font.json.
 *
 * Each glyph packs into one Long, bit (row * WIDTH + col) set where there is ink.
 */
internal object PixelFont {
    const val WIDTH = ${font.w}
    const val HEIGHT = ${font.h}
    const val TRACKING = ${font.tracking}
    const val ADVANCE = WIDTH + TRACKING

    const val INDEX = "${index}"

    val GLYPHS = longArrayOf(
${packed.map(b => '        ' + b.toString() + 'L,').join('\n')}
    )

    private val FALLBACK = INDEX.indexOf('?').coerceAtLeast(0)

    fun glyph(c: Char): Long {
        val i = INDEX.indexOf(c)
        return GLYPHS[if (i >= 0) i else FALLBACK]
    }

    fun ink(g: Long, col: Int, row: Int): Boolean = (g ushr (row * WIDTH + col)) and 1L == 1L

    fun width(text: String, scale: Int): Int =
        if (text.isEmpty()) 0 else (text.length * ADVANCE - TRACKING) * scale
}
`;

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'Frames.kt'), framesKt);
fs.writeFileSync(path.join(OUT, 'SceneMeta.kt'), metaKt);
fs.writeFileSync(path.join(OUT, 'PixelFont.kt'), fontKt);

console.log('generated Frames.kt    (' + frames.length + ' frame(s)' +
  (frames.length ? ' at ' + manifest.width + 'x' + manifest.height : ' - none imported') + ')');
console.log('generated SceneMeta.kt (' + openings.length + ' window(s)' + (moon ? ', moon' : '') + ')');
console.log('generated PixelFont.kt (' + order.length + ' glyphs)');
