'use strict';
// Turns the art data into Kotlin the app compiles against.
//   art/layers.json -> scene/Layers.kt
//   art/font.json   -> scene/PixelFont.kt
// Both outputs are generated - edit the JSON and re-run, never the Kotlin.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'app/src/main/java/com/sylcolabs/weatherpaper/scene');
const PKG = 'package com.sylcolabs.weatherpaper.scene';
const HEADER = '// GENERATED BY tools/gen-kotlin.js - DO NOT EDIT BY HAND.\n';

function read(file, fallback) {
  const p = path.join(ROOT, file);
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : fallback;
}

const f = n => (Number.isInteger(n) ? n.toFixed(1) : String(n)) + 'f';

// ---- layers ----
const manifest = read('art/layers.json', { width: 0, height: 0, anchor: 'bottom', layers: [] });
const layers = manifest.layers || [];

const layersKt = `${HEADER}
${PKG}

import com.sylcolabs.weatherpaper.R

/**
 * The scene, as a stack of images composited back to front.
 *
 * Imported from art/layers/ by tools/import-layers.js. Nothing here assumes anything about what
 * the picture contains - the canvas size comes from the artwork itself, and an empty list simply
 * means no art has been imported yet.
 */
internal object Layers {

    /** The artwork's own pixel dimensions; 0 when nothing has been imported. */
    const val WIDTH = ${manifest.width || 0}
    const val HEIGHT = ${manifest.height || 0}

    /** How the artwork sits in a screen of a different shape once it has been scaled to cover. */
    const val ANCHOR_BOTTOM = ${manifest.anchor !== 'centre' && manifest.anchor !== 'center'}

    /**
     * @param parallax how far this layer slides as the home screen is swiped, in artwork pixels.
     * @param sway amplitude of its idle drift, in artwork pixels. Zero for both means it is still.
     */
    class Layer(val name: String, val resId: Int, val parallax: Float, val sway: Float)

    /** Back to front. */
    val ALL: Array<Layer> = arrayOf(${layers.length === 0 ? ')' : '\n' +
      layers.map(l => `        Layer("${l.name}", R.drawable.${l.resource}, ${f(l.parallax || 0)}, ${f(l.sway || 0)}),`).join('\n') +
      '\n    )'}

    val isEmpty: Boolean get() = ALL.isEmpty()

    /** True while any layer drifts on its own, which is what decides if a redraw loop is needed. */
    val hasMotion: Boolean get() = ALL.any { it.sway != 0f }
}
`;

// ---- font ----
const font = read('art/font.json', { w: 5, h: 7, tracking: 1, glyphs: {} });
const order = Object.keys(font.glyphs);
const packed = order.map(function (ch) {
  const rows = font.glyphs[ch].split('/');
  let bits = 0n;
  for (let r = 0; r < font.h; r++) {
    for (let c = 0; c < font.w; c++) {
      if (rows[r][c] === '#') bits |= 1n << BigInt(r * font.w + c);
    }
  }
  return bits;
});
const index = order.join('').replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$');

const fontKt = `${HEADER}
${PKG}

/**
 * The bitmap font used by the home-screen readout, from art/font.json.
 *
 * Each glyph packs into one Long, bit (row * WIDTH + col) set where there is ink. [INDEX] maps a
 * character to its slot; anything absent falls back to '?'.
 */
internal object PixelFont {
    const val WIDTH = ${font.w}
    const val HEIGHT = ${font.h}
    const val TRACKING = ${font.tracking}
    const val ADVANCE = WIDTH + TRACKING

    const val INDEX = "${index}"

    val GLYPHS = longArrayOf(
${packed.map(b => '        ' + b.toString() + 'L,').join('\n')}
    )

    private val FALLBACK = INDEX.indexOf('?').coerceAtLeast(0)

    fun glyph(c: Char): Long {
        val i = INDEX.indexOf(c)
        return GLYPHS[if (i >= 0) i else FALLBACK]
    }

    /** True where the glyph has ink at (col, row). */
    fun ink(g: Long, col: Int, row: Int): Boolean = (g ushr (row * WIDTH + col)) and 1L == 1L

    fun width(text: String, scale: Int): Int =
        if (text.isEmpty()) 0 else (text.length * ADVANCE - TRACKING) * scale
}
`;

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'Layers.kt'), layersKt);
fs.writeFileSync(path.join(OUT, 'PixelFont.kt'), fontKt);

console.log('generated Layers.kt   (' + layers.length + ' layer(s)' +
  (layers.length ? ' at ' + manifest.width + 'x' + manifest.height : ' - placeholder in use') + ')');
console.log('generated PixelFont.kt (' + order.length + ' glyphs)');
