'use strict';
// Imports the time-of-day frames into the app.
//
//   art/frames/<time>-<condition>.png  ->  art/frames.json + app resources
//
// Each frame is a complete scene. The app blends across two axes - time of day and cloud - so
// every frame must share the same dimensions AND the same geometry. Only the lighting may differ,
// or the forest visibly shifts as the day turns or the weather closes in.
const fs = require('fs');
const path = require('path');
const { decodePNG } = require('./png-decode.js');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'art/frames');
const RES = path.join(ROOT, 'app/src/main/res/drawable-nodpi');
const MANIFEST = path.join(ROOT, 'art/frames.json');

/** The cloud axis, driest first. The app blends along it as cover increases. */
const CONDITIONS = ['clear', 'overcast'];

/**
 * Where each time sits in the day, as a fraction of a full cycle:
 * 0.00 midnight, 0.25 sunrise, 0.50 noon, 0.75 sunset. Wraps.
 */
const DEFAULT_PHASE = {
  night: 0.00, firstlight: 0.19, dawn: 0.25, morning: 0.34,
  midday: 0.50, golden: 0.68, dusk: 0.78, twilight: 0.86,
};

const existing = fs.existsSync(MANIFEST) ? JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) : { frames: [] };
const prior = new Map((existing.frames || []).map(f => [f.name, f]));

const files = fs.existsSync(SRC)
  ? fs.readdirSync(SRC).filter(f => f.toLowerCase().endsWith('.png')).sort()
  : [];

if (fs.existsSync(RES)) {
  for (const f of fs.readdirSync(RES)) if (/^frame_/.test(f)) fs.unlinkSync(path.join(RES, f));
}

if (files.length === 0) {
  fs.writeFileSync(MANIFEST, JSON.stringify(
    { width: 0, height: 0, anchor: 'bottom', conditions: CONDITIONS, frames: [] }, null, 2) + '\n');
  console.log('No PNGs in art/frames/ - nothing imported.');
  process.exit(0);
}

fs.mkdirSync(RES, { recursive: true });

let width = 0, height = 0;
const byTime = new Map();
const errors = [];

for (const file of files) {
  const stem = file.replace(/\.png$/i, '');
  const dash = stem.lastIndexOf('-');
  const time = dash < 0 ? stem : stem.slice(0, dash);
  const cond = dash < 0 ? 'clear' : stem.slice(dash + 1);
  if (!CONDITIONS.includes(cond)) {
    errors.push(file + ': unknown condition "' + cond + '". Expected one of: ' + CONDITIONS.join(', '));
    continue;
  }

  let img;
  try {
    img = decodePNG(fs.readFileSync(path.join(SRC, file)));
  } catch (e) {
    errors.push(file + ': ' + e.message);
    continue;
  }
  if (width === 0) { width = img.width; height = img.height; }
  if (img.width !== width || img.height !== height) {
    errors.push(file + ' is ' + img.width + 'x' + img.height + ' but ' + files[0] + ' is ' +
      width + 'x' + height + '. Every frame must share one canvas.');
    continue;
  }

  const res = 'frame_' + (time + '_' + cond).toLowerCase().replace(/[^a-z0-9]+/g, '_');
  fs.copyFileSync(path.join(SRC, file), path.join(RES, res + '.png'));
  if (!byTime.has(time)) byTime.set(time, {});
  byTime.get(time)[cond] = res;
}

const frames = [];
for (const [time, resources] of byTime) {
  const missing = CONDITIONS.filter(c => !resources[c]);
  if (missing.length) {
    // A time with only some conditions would blend into a hole, so this is fatal rather than
    // silently substituted - the wrong frame appearing under cloud is far harder to diagnose.
    errors.push(time + ': missing the ' + missing.join(' and ') + ' variant. Every time needs all ' +
      CONDITIONS.length + ': ' + CONDITIONS.join(', '));
    continue;
  }
  const p = prior.get(time) || {};
  const phase = p.phase !== undefined ? p.phase
    : DEFAULT_PHASE[time] !== undefined ? DEFAULT_PHASE[time] : null;
  if (phase === null) {
    errors.push(time + ': no day phase known. Add a "phase" (0..1) for it in art/frames.json, ' +
      'or name it one of: ' + Object.keys(DEFAULT_PHASE).join(', '));
    continue;
  }
  frames.push({ name: time, phase: phase, resources: resources });
}

if (errors.length) {
  for (const e of errors) console.error('error: ' + e);
  console.error('\n' + errors.length + ' problem(s). Nothing was written.');
  process.exit(1);
}

frames.sort((a, b) => a.phase - b.phase);

fs.writeFileSync(MANIFEST, JSON.stringify({
  _comment: 'Generated by tools/import-frames.js. phase is position in the day: 0 midnight, ' +
    '0.25 sunrise, 0.5 noon, 0.75 sunset. The app blends between adjacent times, wrapping past ' +
    'midnight, and between conditions as cloud cover rises. Edit phase by hand; it survives ' +
    're-imports.',
  width: width,
  height: height,
  anchor: existing.anchor || 'bottom',
  conditions: CONDITIONS,
  frames: frames,
}, null, 2) + '\n');

console.log('imported ' + frames.length + ' time(s) x ' + CONDITIONS.length + ' condition(s) at ' +
  width + 'x' + height);
for (const f of frames) {
  console.log('  phase ' + f.phase.toFixed(2) + '  ' + f.name.padEnd(11) +
    '-> ' + CONDITIONS.map(c => f.resources[c]).join(', '));
}
