'use strict';
// Imports a layered scene exported from Aseprite (or anything else) into the app.
//
//   1. put your exported PNGs in art/layers/, named so they sort back-to-front
//   2. node tools/import-layers.js
//   3. node tools/gen-kotlin.js
//
// Makes no assumptions about what is in the picture: any size, any colours, any number of
// layers. The only requirement is that every layer shares the same dimensions, because they
// are composited on top of one another.
const fs = require('fs');
const path = require('path');
const { decodePNG } = require('./png-decode.js');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'art/layers');
const RES = path.join(ROOT, 'app/src/main/res/drawable-nodpi');
const MANIFEST = path.join(ROOT, 'art/layers.json');

/** Android resource names: lowercase, digits and underscores only, must not start with a digit. */
function resourceName(index, base) {
  const slug = base.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'layer';
  return 'layer_' + String(index).padStart(2, '0') + '_' + slug;
}

const existing = fs.existsSync(MANIFEST) ? JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) : { layers: [] };
const previous = new Map((existing.layers || []).map(function (l) { return [l.source, l]; }));

const files = fs.existsSync(SRC)
  ? fs.readdirSync(SRC).filter(function (f) { return f.toLowerCase().endsWith('.png'); }).sort()
  : [];

// Clear out resources from a previous import so removed layers do not linger in the APK.
if (fs.existsSync(RES)) {
  for (const f of fs.readdirSync(RES)) {
    if (/^layer_\d\d_/.test(f)) fs.unlinkSync(path.join(RES, f));
  }
}

if (files.length === 0) {
  fs.writeFileSync(MANIFEST, JSON.stringify({ width: 0, height: 0, anchor: 'bottom', layers: [] }, null, 2) + '\n');
  console.log('No PNGs in art/layers/ - nothing imported.');
  console.log('The app will render its placeholder until you add some.');
  process.exit(0);
}

fs.mkdirSync(RES, { recursive: true });

let width = 0, height = 0;
const layers = [];
const errors = [];

files.forEach(function (file, i) {
  const full = path.join(SRC, file);
  let img;
  try {
    img = decodePNG(fs.readFileSync(full));
  } catch (e) {
    errors.push(file + ': ' + e.message);
    return;
  }
  if (width === 0) { width = img.width; height = img.height; }
  if (img.width !== width || img.height !== height) {
    errors.push(file + ' is ' + img.width + 'x' + img.height + ', but ' + files[0] + ' is ' +
      width + 'x' + height + '. Every layer must share one canvas - re-export with trimming OFF.');
    return;
  }

  const base = file.replace(/\.png$/i, '').replace(/^\d+[-_ ]*/, '');
  const res = resourceName(i + 1, base);
  fs.copyFileSync(full, path.join(RES, res + '.png'));

  // Per-layer motion is carried across imports so tuning is not lost on a re-export.
  const prior = previous.get(file) || {};
  layers.push({
    source: file,
    name: base,
    resource: res,
    parallax: prior.parallax !== undefined ? prior.parallax : 0,
    sway: prior.sway !== undefined ? prior.sway : 0,
  });
});

if (errors.length) {
  for (const e of errors) console.error('error: ' + e);
  console.error('\n' + errors.length + ' problem(s). Nothing was written.');
  process.exit(1);
}

fs.writeFileSync(MANIFEST, JSON.stringify({
  _comment: 'Generated by tools/import-layers.js. Layers composite in array order, back to front. ' +
    'parallax and sway are edited by hand and preserved across re-imports.',
  width: width,
  height: height,
  anchor: existing.anchor || 'bottom',
  layers: layers,
}, null, 2) + '\n');

console.log('imported ' + layers.length + ' layer(s) at ' + width + 'x' + height);
layers.forEach(function (l, i) {
  console.log('  ' + String(i + 1).padStart(2) + '. ' + l.source.padEnd(28) + '-> ' + l.resource);
});
console.log('\nnext: node tools/gen-kotlin.js');
