'use strict';
// Imports the time-of-day frames into the app.
//
//   art/frames/*.png  ->  art/frames.json + app resources
//
// Each frame is a complete scene. The app cross-fades between the two frames either side of the
// current time, so every frame must share the same dimensions AND the same geometry - only the
// lighting should differ, or the forest visibly shifts as the day turns.
const fs = require('fs');
const path = require('path');
const { decodePNG } = require('./png-decode.js');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'art/frames');
const RES = path.join(ROOT, 'app/src/main/res/drawable-nodpi');
const MANIFEST = path.join(ROOT, 'art/frames.json');

/**
 * Where each frame sits in the day, as a fraction of a full cycle:
 * 0.00 midnight, 0.25 sunrise, 0.50 noon, 0.75 sunset. Wraps.
 */
const DEFAULT_PHASE = {
  night: 0.00, dawn: 0.25, morning: 0.34, midday: 0.50, golden: 0.68, dusk: 0.78,
};

const existing = fs.existsSync(MANIFEST) ? JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) : { frames: [] };
const prior = new Map((existing.frames || []).map(f => [f.source, f]));

const files = fs.existsSync(SRC)
  ? fs.readdirSync(SRC).filter(f => f.toLowerCase().endsWith('.png')).sort()
  : [];

if (fs.existsSync(RES)) {
  for (const f of fs.readdirSync(RES)) if (/^frame_/.test(f)) fs.unlinkSync(path.join(RES, f));
}

if (files.length === 0) {
  fs.writeFileSync(MANIFEST, JSON.stringify({ width: 0, height: 0, anchor: 'bottom', frames: [] }, null, 2) + '\n');
  console.log('No PNGs in art/frames/ - nothing imported.');
  process.exit(0);
}

fs.mkdirSync(RES, { recursive: true });

let width = 0, height = 0;
const frames = [];
const errors = [];

for (const file of files) {
  const name = file.replace(/\.png$/i, '').replace(/^\d+[-_ ]*/, '');
  let img;
  try {
    img = decodePNG(fs.readFileSync(path.join(SRC, file)));
  } catch (e) {
    errors.push(file + ': ' + e.message);
    continue;
  }
  if (width === 0) { width = img.width; height = img.height; }
  if (img.width !== width || img.height !== height) {
    errors.push(file + ' is ' + img.width + 'x' + img.height + ' but ' + files[0] + ' is ' +
      width + 'x' + height + '. Every frame must share one canvas.');
    continue;
  }

  const p = prior.get(file) || {};
  const phase = p.phase !== undefined ? p.phase
    : DEFAULT_PHASE[name] !== undefined ? DEFAULT_PHASE[name] : null;
  if (phase === null) {
    errors.push(file + ': no day phase known for "' + name + '". Add a "phase" (0..1) for it in ' +
      'art/frames.json, or name it one of: ' + Object.keys(DEFAULT_PHASE).join(', '));
    continue;
  }

  const res = 'frame_' + name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  fs.copyFileSync(path.join(SRC, file), path.join(RES, res + '.png'));
  frames.push({ source: file, name: name, resource: res, phase: phase });
}

if (errors.length) {
  for (const e of errors) console.error('error: ' + e);
  console.error('\n' + errors.length + ' problem(s). Nothing was written.');
  process.exit(1);
}

frames.sort((a, b) => a.phase - b.phase);

fs.writeFileSync(MANIFEST, JSON.stringify({
  _comment: 'Generated by tools/import-frames.js. phase is position in the day: 0 midnight, ' +
    '0.25 sunrise, 0.5 noon, 0.75 sunset. The app cross-fades between adjacent frames, wrapping ' +
    'past midnight. Edit phase by hand; it survives re-imports.',
  width: width,
  height: height,
  anchor: existing.anchor || 'bottom',
  frames: frames,
}, null, 2) + '\n');

console.log('imported ' + frames.length + ' frame(s) at ' + width + 'x' + height);
for (const f of frames) {
  console.log('  phase ' + f.phase.toFixed(2) + '  ' + f.name.padEnd(10) + '-> ' + f.resource);
}
